import Head from 'next/head';
import MainLayout from '../src/layouts/MainLayout';
import HomePage from './home';

export default function Home() {
  return (
    <div>
      <Head>
        <title>SOIOT APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <HomePage />
      </MainLayout>
    </div>
  );
}
